name: Production Deploy Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploiement vers serveur de production
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, zip, gd
          tools: composer:v2

      - name: Nettoyage pre-deploiement
        run: |
          rm -rf vendor
          rm -rf var/cache/*
          rm -rf var/log/*
          rm -rf tests/
          rm -rf node_modules || true
          rm -rf .git
          rm -rf .github

      - name: Generation metadata deploiement
        run: |
          echo "Build date: $(date)" > build-info.txt
          echo "Git commit: ${{ github.sha }}" >> build-info.txt
          echo "Branch: ${{ github.ref_name }}" >> build-info.txt

      - name: Transfert fichiers vers serveur
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT || 21 }}
          protocol: ftp
          server-dir: ${{ secrets.FTP_REMOTE_DIR || '/' }}
          local-dir: ./
          timeout: 60000
          log-level: verbose
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/vendor/**
            **/tests/**
            **/var/**
            **/*.yml
            **/*.yaml
            **/*.xml
            **/*.lock
            **/*.md
            .env.test*
            .env.local
            phpunit.xml.dist

      - name: Resume du deploiement
        run: |
          echo "Transfert FTP effectue avec succes"
          echo "Timestamp: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "Destination: ${{ secrets.FTP_SERVER }}"
          echo "Version: ${{ github.sha }}"